---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/forwardingrule
  name: allow-iap-ssh
spec:
  forProvider:
    allow:
      - ports:
          - "22"
        protocol: tcp
    direction: INGRESS
    networkRef:
      name: dev-network
    sourceRanges:
      - 35.235.240.0/20
    targetTags:
      - allow-ssh
