---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Router
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/router
  name: dev-net-router
spec:
  forProvider:
    bgp:
      - asn: 64514
    networkRef:
      name: dev-network
    region: us-central1
