---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/forwardingrule
  name: allow-all-internal
spec:
  forProvider:
    allow:
      - ports:
          - "0-65535"
        protocol: tcp
      - ports:
          - "0-65535"
        protocol: udp
      - protocol: icmp
    direction: INGRESS
    networkRef:
      name: dev-network
    sourceRanges:
      - 10.128.0.0/9
