---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: RouterNAT
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/routernat
  name: dev-net-routernat
spec:
  forProvider:
    logConfig:
      - enable: true
        filter: ERRORS_ONLY
    natIpAllocateOption: AUTO_ONLY
    region: us-central1
    routerRef:
      name: dev-net-router
    sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
