---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: google-postgresql
  labels:
    provider: google
    db: postgresql
spec:
  compositeTypeRef:
    apiVersion: maxwilson.dev/v1alpha1
    kind: SQL
  resources:
    - name: sql
      base:
        apiVersion: sql.gcp.upbound.io/v1beta1
        kind: DatabaseInstance
        spec:
          forProvider:
            databaseVersion: POSTGRES_15
            deletionProtection: false
            region: us-central1
            rootPasswordSecretRef:
              key: password
              name: db-inst-01-admin
              namespace: a-team
            settings:
              - availabilityType: REGIONAL
                backupConfiguration:
                  - enabled: true
                    binaryLogEnabled: false
                diskSize: 10
                edition: ENTERPRISE
                # insightsConfig:
                #   - queryInsightsEnabled: true
                #     queryStringLength: 4500
                #     recordApplicationTags: true
                ipConfiguration:
                  - ipv4Enabled: false
                    privateNetworkRef:
                      name: dev-network
                tier: db-f1-micro
          publishConnectionDetailsTo:
            name: db-inst-01-connection
    - name: user
      base:
        apiVersion: sql.gcp.upbound.io/v1beta1
        kind: User
        spec:
          forProvider:
            passwordSecretRef:
              key: password
              name: db-inst-01-admin
              namespace: a-team
            instanceSelector:
              matchControllerRef: true
