# ---
# apiVersion: container.gcp.upbound.io/v1beta1
# kind: Cluster
# metadata:
#   annotations:
#     meta.upbound.io/id: container/v1beta1/cluster
#   name: cluster
# spec:
#   forProvider:
#     # costManagementConfig:
#     #   - enabled: true
#     # clusterAutoscaling:
#     #   - autoProvisioningDefaults:
#     #       - management:
#     #           - autoRepair: true
#     #             autoUpgrade: true
#     #         upgradeSettings:
#     #           - maxUnavailable: 1
#     #     # Enabled is implied in autopilot
#     #     # enabled: true
#     #     resourceLimits:
#     #       - maximum: 8
#     #         minimum: 1
#     #         resourceType: cpu
#     #       - maximum: 32
#     #         minimum: 1
#     #         resourceType: memory
#     #     serviceAccountRef:
#     #       name: gke-sa
#     # databaseEncryption:
#     #   - keyName: projects/${KEY_PROJECT_ID}/locations/${GKE_CLUSTER_REGION}/keyRings/${KEY_RING}/cryptoKeys/${KEY_NAME}
#     deletionProtection: false
#     enableAutopilot: true
#     enableIntranodeVisibility: true
#     # fleet:
#     #   - project: ${ANTHOS_FLEET_HOST_PROJECT}
#     # gatewayApiConfig:
#     #   - channel: CHANNEL_STANDARD
#     initialNodeCount: 1
#     ipAllocationPolicy:
#       - {}
#     # Autopilot must be regional
#     location: us-central1
#     #location: us-central1-b
#     # loggingConfig:
#     #   - enableComponents:
#     #       - SYSTEM_COMPONENTS
#     #       - APISERVER
#     #       - CONTROLLER_MANAGER
#     #       - SCHEDULER
#     #       - WORKLOADS
#     # maintenancePolicy:
#     #   - dailyMaintenanceWindow:
#     #       - startTime: 06:00
#     masterAuthorizedNetworksConfig:
#       - {}
#     # monitoringConfig:
#     #   - managedPrometheus:
#     #       - enabled: true
#         # Datapath is enabled in autopilot by default
#         # advancedDatapathObservabilityConfig:
#         #   - enableMetrics: true
#     # NetworkPolicy is already enabled when datapath/plane is enabled.
#     # networkPolicy:
#     #   - enabled: true
#     networkRef:
#       name: dev-network
#     # nodeConfig:
#     #   - serviceAccountRef:
#     #       name: gke-sa
#     #     spot: true
#     privateClusterConfig:
#       - enablePrivateNodes: true
#         enablePrivateEndpoint: true
#     project: crossplane-probe
#     removeDefaultNodePool: true
#     verticalPodAutoscaling:
#       - enabled: true
#     workloadIdentityConfig:
#       - workloadPool: crossplane-probe.svc.id.goog
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  name: dev-network
spec:
  forProvider: {}
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/forwardingrule
  name: allow-all-internal
spec:
  forProvider:
    allow:
      - ports:
          - "0-65535"
        protocol: tcp
      - ports:
          - "0-65535"
        protocol: udp
      - protocol: icmp
    direction: INGRESS
    networkRef:
      name: dev-network
    sourceRanges:
      - 10.128.0.0/9
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/forwardingrule
  name: allow-iap-ssh
spec:
  forProvider:
    allow:
      - ports:
          - "22"
        protocol: tcp
    direction: INGRESS
    networkRef:
      name: dev-network
    sourceRanges:
      - 35.235.240.0/20
    targetTags:
      - allow-ssh
# ---
# apiVersion: compute.gcp.upbound.io/v1beta1
# kind: Instance
# metadata:
#   name: gke-bastion
# spec:
#   forProvider:
#     allowStoppingForUpdate: true
#     bootDisk:
#       - initializeParams:
#           - image: debian-cloud/debian-11
#     desiredStatus: RUNNING
#     machineType: e2-micro
#     metadataStartupScript: |-
#       apt-get update
#       apt-get install -y kubectl google-cloud-sdk-gke-gcloud-auth-plugin
#     networkInterface:
#       - networkRef:
#           name: dev-network
#     serviceAccount:
#       - emailRef:
#           name: gke-bastion
#         scopes:
#           - cloud-platform
#     tags:
#       - allow-ssh
#     zone: us-central1-b
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: GlobalAddress
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/globaladdress
  name: google-managed-services-dev-network
spec:
  forProvider:
    addressType: INTERNAL
    networkRef:
      name: dev-network
    prefixLength: 16
    purpose: VPC_PEERING
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: RouterNAT
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/routernat
  name: dev-net-routernat
spec:
  forProvider:
    logConfig:
      - enable: true
        filter: ERRORS_ONLY
    natIpAllocateOption: AUTO_ONLY
    region: us-central1
    routerRef:
      name: dev-net-router
    sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Router
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/router
  name: dev-net-router
spec:
  forProvider:
    bgp:
      - asn: 64514
    networkRef:
      name: dev-network
    region: us-central1
# ---
# apiVersion: cloudplatform.gcp.upbound.io/v1beta1
# kind: ServiceAccount
# metadata:
#   annotations:
#     meta.upbound.io/id: cloudplatform/v1beta1/serviceaccount
#   name: gke-bastion
# spec:
#   forProvider:
#     displayName: Service Account for GKE access
# ---
# apiVersion: cloudplatform.gcp.upbound.io/v1beta1
# kind: ProjectIAMMember
# metadata:
#   annotations:
#     meta.upbound.io/id: cloudplatform/v1beta1/projectiammember
#   name: sql-bastion-iam
# spec:
#   forProvider:
#     member: serviceAccount:sql-bastion@crossplane-probe.iam.gserviceaccount.com
#     project: crossplane-probe
#     role: roles/cloudsql.client
# ---
# apiVersion: cloudplatform.gcp.upbound.io/v1beta1
# kind: ServiceAccount
# metadata:
#   annotations:
#     meta.upbound.io/id: cloudplatform/v1beta1/serviceaccount
#   name: sql-bastion
# spec:
#   forProvider:
#     displayName: Service Account for SQL access
---
apiVersion: servicenetworking.gcp.upbound.io/v1beta1
kind: Connection
metadata:
  annotations:
    meta.upbound.io/id: servicenetworking/v1beta1/connection
  name: service-connection
spec:
  forProvider:
    networkRef:
      name: dev-network
    reservedPeeringRangesRefs:
      - name: google-managed-services-dev-network
    service: servicenetworking.googleapis.com
# ---
# apiVersion: compute.gcp.upbound.io/v1beta1
# kind: Instance
# metadata:
#   name: sql-bastion
# spec:
#   forProvider:
#     allowStoppingForUpdate: true
#     bootDisk:
#       - initializeParams:
#           - image: debian-cloud/debian-11
#     desiredStatus: RUNNING
#     machineType: e2-micro
#     metadataStartupScript: |-
#       apt-get update
#       apt-get install -y postgresql-client
#       curl -o /usr/bin/cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.10.1/cloud-sql-proxy.linux.amd64
#       chmod +x /usr/bin/cloud-sql-proxy
#     networkInterface:
#       - networkRef:
#           name: dev-network
#     serviceAccount:
#       - emailRef:
#           name: sql-bastion
#         scopes:
#           - https://www.googleapis.com/auth/sqlservice.admin
#     tags:
#       - allow-ssh
#     zone: us-central1-b
# ---
# apiVersion: sql.gcp.upbound.io/v1beta1
# kind: DatabaseInstance
# metadata:
#   annotations:
#     meta.upbound.io/id: sql/v1beta1/databaseinstance
#   name: db-inst-02
# spec:
#   forProvider:
#     databaseVersion: POSTGRES_15
#     deletionProtection: false
#     region: us-central1
#     rootPasswordSecretRef:
#       key: password
#       name: db-inst-02-admin
#       namespace: a-team
#     settings:
#       - diskSize: 10
#         edition: ENTERPRISE
#         insightsConfig:
#           - queryInsightsEnabled: true
#             queryStringLength: 4500
#             recordApplicationTags: true
#         ipConfiguration:
#           - ipv4Enabled: false
#             privateNetworkRef:
#               name: dev-network
#         tier: db-f1-micro
#   publishConnectionDetailsTo:
#     name: db-inst-02-connection
