---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: sqls.maxwilson.dev
spec:
  group: maxwilson.dev
  names:
    kind: SQL
    plural: sqls
  claimNames:
    kind: SQLClaim
    plural: sqlclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: Database ID
                parameters:
                  type: object
                  properties:
                    version:
                      description: The DB version depends on the DB type and versions available in the selected provider.
                      type: string
                    size:
                      description: "Supported sizes: small, medium, large. Defaults to `small`"
                      type: string
                      default: small
                    # public:
                    #   description: "If true, this instance will be provisioned a public IP address. Defaults to `false` for security." 
                    #   type: boolean
                    #   default: false
                  required:
                    - version
              required:
                - parameters
